#---------------------------------------------------------------------
#    config for alacritty
#    reference:  https://alacritty.org/config-alacritty.html
#---------------------------------------------------------------------

# Live config reload (changes require restart)
live_config_reload = true

# https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/breeze.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 30 }
dynamic_padding = true
decorations = "Full"
opacity = 1.0
# blur = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular"}
size = 12.0
offset = {x = 0, y = 8}

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
    #---------------------------------------------------------------------
    #    key binding for neovim
    { key="CapsLock", chars = "\u001b"},

    #---------------------------------------------------------------------
    #    key binding for tmux
    # 垂直创建窗格
    { key = "D", mods = "Command", chars = "\u0002\u0025" },
    # 水平创建窗格
    { key = "D", mods = "Command|Shift", chars = "\u0002\"" },

    { key = "ArrowLeft",        mods = "Command|Shift", chars = "\u0002H"           }, 
    { key = "ArrowDown",        mods = "Command|Shift", chars = "\u0002J"           }, 
    { key = "ArrowUp",        mods = "Command|Shift", chars = "\u0002K"           }, 
    { key = "ArrowRight",        mods = "Command|Shift", chars = "\u0002L"           }, 

    # 创建新窗口
    { key = "t", mods = "Command|Shift", chars = "\u0002c" },
 ]




